### ISSUE TITLE
Request: Additional Lat/Lon Formats

### ISSUE THREAD

**Issue by wraith70** [uriba107/DCS-Hound#12]
A feature request. DCS uses 3 different L/L formats:

DMS - For the F/A-18C, coordinates are formatted as DD°MM'SS.ss"
DDM - For the F-16C, coordinates are formatted as DD°MM.mmm'
DD - For the M2000C, coordinates are formatted as DD.MM.mm

Currently only DMS. Could the other 2 formats be included?
Thanks.

**Comment by uriba107** [comment]
Hi Wraith. Thank you for this!
A change for this is planned for next update because it requires quite a few changes behind the scenes. 

it only need to support two types.
DMS and DMM

system accuracy does not justify DMS.s just too many digits :)

DMS = DD°MM'SS
DMM = DD°MM.mmm'

what you called DD (for the M2K) is just DMM with less precision. you drop the last digit.

in the meanwhile.
conversion between DMS (currently provided format) to DMM requires some basic brain power
"formal" math is S/60 which is quite hard.

but in fact every 6 seconds is 0.1 Minute.
so you just find the nearest multiple of 6 and that's your decimal minute. then just round it up or down. system is not that accurate to care if you convert 16 seconds to 0.26 or 0.27 (sure, throw 0.265 if you want :))

30 seconds = 0.5
45 seconds = 0.75
18 seconds = 0.3

Uri
