### ISSUE TITLE
enableMarkers and SetMarkerType(POLYGON) crashes clients

### ISSUE THREAD

**Issue by Toumal** [uriba107/DCS-Hound#30]
Hi,

I have a mission in which I use the following:

Elint_red:setMarkerType(HOUND.MARKER.POLYGON)
Elint_red:enableMarkers()

After lots of debugging I found that this crashes the client in a kind of endless loop on my mission, if you play on red. Blue has no markers set up, and the F10 map does not crash for them. This appears to coincide with ELINT wanting to draw map markers. Is this a known issue? Should I use a different marker type, and if so, which one?

**Comment by uriba107** [comment]
Hi thanks for the report!
I'll try and replicate soon. Just any red elint markers crash it?

There is an issue when using Polygons mainly due to the DCS optimization or lack of... You can Try Diamond (default) or even circle to see if that helps the number of points the client needs to draw had been reported to cause stutters on client side. Maybe crashes are OOM related?

In the past there was also a crash related to markers and Viggens. Where Viggen pilots would CTD when trying to add a marker. But that has been resolved. In a very early build by changing the way Hound manages map marker IDs.

**Comment by uriba107** [comment]
see issue #28 
0.2.2 will allow mission builder to use Hound internal Counters rather then the default counter logic
